### ISSUE TITLE
编译过程始终为单线程

### ISSUE THREAD

**Issue by mujianwu** [bigsaltyfishes/Kernel-Dimension2#1]
编译过程始终为单线程，-jxx也没有作用😭

**Comment by bigsaltyfishes** [comment]
这个你得去调内核的构建参数，你试试设置环境变量 `MAKEOPTS="-j$(nproc --all)"`

**Comment by mujianwu** [comment]
感谢大佬，确实好了，但是更新了一下KSU然后卡一了，不知道您是否方便留个其他平台的联系方式呢？🥰

**Comment by bigsaltyfishes** [comment]
KSU的问题我觉得你应该去KSU那边反馈，然后KSU的那个提交是这个：https://github.com/bigsaltyfishes/Kernel-Dimension2/commit/49f96e9c0f2164273cbdfb5df0b5f6b5286153b1
有需要可以把它 revert 掉重新弄，因为我设备已经出掉了，现在没办法也不打算继续维护这个内核，能提供的帮助有限

**Comment by mujianwu** [comment]
看您酷安上说了，之前在酷安就跟您反馈过这个问题，您一直没回我😭。看您购入了一个WOA设备还想和您交流一下呢。
刚刚我把KSU去掉重新跑的也是卡一不知道是为啥，之前全程单线程跑的也是开不开😭

**Comment by bigsaltyfishes** [comment]
因为最近没怎么上酷安了，卡一的话你看看你内核模块安装了没有，因为集成模块进内核有资源争用现象，这个是上游的问题，我就弄成内核模块等到用户空间启动的时候再统一载入了，现在我没有设备也不清楚你什么情况

**Comment by mujianwu** [comment]
感谢大佬，我再折腾折腾😘
